# Generated by Django 3.1.1 on 2021-01-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='pst_name',
            field=models.CharField(default=1, max_length=150, verbose_name='Founder Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='pst_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Founder Image'),
        ),
        migrations.AlterField(
            model_name='about',
            name='pst_title',
            field=models.CharField(max_length=150, verbose_name='Founder Title'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='pst_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Hotel Image'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='pst_title',
            field=models.CharField(max_length=150, verbose_name='Hotel Name'),
        ),
    ]
