# Generated by Django 3.1.1 on 2021-01-08 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0002_auto_20210107_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blg_title', models.CharField(max_length=150, verbose_name='Blog Title')),
                ('blg_image', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Blog Image')),
                ('appear_home', models.CharField(choices=[('Feature', 'Appear on home'), ('No Feature', "Don't show on home"), ('', 'Please Choose')], default='', max_length=50)),
                ('blg_content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cat_id', models.ManyToManyField(to='frontend.Category', verbose_name='Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
    ]
