# Generated by Django 3.1.1 on 2021-01-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default=1, max_length=150, verbose_name='User Name'),
            preserve_default=False,
        ),
    ]
