# Generated by Django 3.1.1 on 2021-01-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_remove_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='featured',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='sponsored',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.TextField(verbose_name='Content'),
        ),
    ]
