# Generated by Django 3.1.1 on 2021-01-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_auto_20210117_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blgcat_name', models.CharField(max_length=100, verbose_name=' Blog Category Name')),
                ('blgcat_desc', models.TextField(blank=True, null=True, verbose_name='Blog Category Description')),
            ],
            options={
                'verbose_name_plural': 'Blog Category',
            },
        ),
        migrations.DeleteModel(
            name='Blog_Category',
        ),
        migrations.AlterField(
            model_name='blog',
            name='cat_id',
            field=models.ManyToManyField(to='frontend.BlogCategory', verbose_name='Category'),
        ),
    ]
