# Generated by Django 3.1.1 on 2021-01-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_auto_20210117_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcategory',
            old_name='blgcat_desc',
            new_name='cat_desc',
        ),
        migrations.RenameField(
            model_name='blogcategory',
            old_name='blgcat_name',
            new_name='cat_name',
        ),
    ]
