# Generated by Django 3.1.1 on 2021-01-19 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_auto_20210118_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='User Image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(max_length=150, verbose_name='User Name'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150, verbose_name='User Name')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('review_content', models.TextField(verbose_name='Your Review')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='frontend.hotel')),
            ],
        ),
    ]
